// Mocks generated by Mockito 5.4.4 from annotations
// in flutter_clean_architecture/test/presentation/bloc/search/search_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dartz/dartz.dart' as _i3;
import 'package:flutter_clean_architecture/core/failure.dart' as _i6;
import 'package:flutter_clean_architecture/domain/entities/apod_entity.dart'
    as _i10;
import 'package:flutter_clean_architecture/domain/repositories/search/search_repository.dart'
    as _i2;
import 'package:flutter_clean_architecture/domain/usecases/core/usecase.dart'
    as _i7;
import 'package:flutter_clean_architecture/domain/usecases/search/fetch_apod_by_range.dart'
    as _i9;
import 'package:flutter_clean_architecture/domain/usecases/search/fetch_search_history.dart'
    as _i4;
import 'package:flutter_clean_architecture/domain/usecases/search/update_search_history.dart'
    as _i8;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeSearchRepository_0 extends _i1.SmartFake
    implements _i2.SearchRepository {
  _FakeSearchRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [FetchSearchHistory].
///
/// See the documentation for Mockito's code generation for more information.
class MockFetchSearchHistory extends _i1.Mock
    implements _i4.FetchSearchHistory {
  @override
  _i2.SearchRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeSearchRepository_0(
          this,
          Invocation.getter(#repository),
        ),
        returnValueForMissingStub: _FakeSearchRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.SearchRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, List<String>>> call(
          _i7.NoParameter? parameter) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [parameter],
        ),
        returnValue: _i5.Future<_i3.Either<_i6.Failure, List<String>>>.value(
            _FakeEither_1<_i6.Failure, List<String>>(
          this,
          Invocation.method(
            #call,
            [parameter],
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i3.Either<_i6.Failure, List<String>>>.value(
                _FakeEither_1<_i6.Failure, List<String>>(
          this,
          Invocation.method(
            #call,
            [parameter],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, List<String>>>);
}

/// A class which mocks [UpdateSearchHistory].
///
/// See the documentation for Mockito's code generation for more information.
class MockUpdateSearchHistory extends _i1.Mock
    implements _i8.UpdateSearchHistory {
  @override
  _i2.SearchRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeSearchRepository_0(
          this,
          Invocation.getter(#repository),
        ),
        returnValueForMissingStub: _FakeSearchRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.SearchRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, List<String>>> call(
          List<String>? parameter) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [parameter],
        ),
        returnValue: _i5.Future<_i3.Either<_i6.Failure, List<String>>>.value(
            _FakeEither_1<_i6.Failure, List<String>>(
          this,
          Invocation.method(
            #call,
            [parameter],
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i3.Either<_i6.Failure, List<String>>>.value(
                _FakeEither_1<_i6.Failure, List<String>>(
          this,
          Invocation.method(
            #call,
            [parameter],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, List<String>>>);
}

/// A class which mocks [FetchApodByRange].
///
/// See the documentation for Mockito's code generation for more information.
class MockFetchApodByRange extends _i1.Mock implements _i9.FetchApodByRange {
  @override
  _i2.SearchRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeSearchRepository_0(
          this,
          Invocation.getter(#repository),
        ),
        returnValueForMissingStub: _FakeSearchRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.SearchRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, List<_i10.ApodEntity>>> call(
          String? parameter) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [parameter],
        ),
        returnValue:
            _i5.Future<_i3.Either<_i6.Failure, List<_i10.ApodEntity>>>.value(
                _FakeEither_1<_i6.Failure, List<_i10.ApodEntity>>(
          this,
          Invocation.method(
            #call,
            [parameter],
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i3.Either<_i6.Failure, List<_i10.ApodEntity>>>.value(
                _FakeEither_1<_i6.Failure, List<_i10.ApodEntity>>(
          this,
          Invocation.method(
            #call,
            [parameter],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, List<_i10.ApodEntity>>>);

  @override
  _i3.Either<_i6.Failure, Map<String, dynamic>> toStandardQuery(
          String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #toStandardQuery,
          [query],
        ),
        returnValue: _FakeEither_1<_i6.Failure, Map<String, dynamic>>(
          this,
          Invocation.method(
            #toStandardQuery,
            [query],
          ),
        ),
        returnValueForMissingStub:
            _FakeEither_1<_i6.Failure, Map<String, dynamic>>(
          this,
          Invocation.method(
            #toStandardQuery,
            [query],
          ),
        ),
      ) as _i3.Either<_i6.Failure, Map<String, dynamic>>);
}
