// Mocks generated by Mockito 5.4.4 from annotations
// in flutter_clean_architecture/test/data/repository/bookmarks/bookmarks_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:flutter_clean_architecture/core/success.dart' as _i2;
import 'package:flutter_clean_architecture/data/datasources/bookmarks/bookmarks_datasource.dart'
    as _i3;
import 'package:flutter_clean_architecture/data/models/apod_model.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeApodSave_0 extends _i1.SmartFake implements _i2.ApodSave {
  _FakeApodSave_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeApodRemove_1 extends _i1.SmartFake implements _i2.ApodRemove {
  _FakeApodRemove_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [BookmarksDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockBookmarksDataSource extends _i1.Mock
    implements _i3.BookmarksDataSource {
  @override
  _i4.Future<_i2.ApodSave> saveApod(_i5.ApodModel? apodModel) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveApod,
          [apodModel],
        ),
        returnValue: _i4.Future<_i2.ApodSave>.value(_FakeApodSave_0(
          this,
          Invocation.method(
            #saveApod,
            [apodModel],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.ApodSave>.value(_FakeApodSave_0(
          this,
          Invocation.method(
            #saveApod,
            [apodModel],
          ),
        )),
      ) as _i4.Future<_i2.ApodSave>);

  @override
  _i4.Future<_i2.ApodRemove> removeSavedApod(String? apodDate) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeSavedApod,
          [apodDate],
        ),
        returnValue: _i4.Future<_i2.ApodRemove>.value(_FakeApodRemove_1(
          this,
          Invocation.method(
            #removeSavedApod,
            [apodDate],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.ApodRemove>.value(_FakeApodRemove_1(
          this,
          Invocation.method(
            #removeSavedApod,
            [apodDate],
          ),
        )),
      ) as _i4.Future<_i2.ApodRemove>);

  @override
  _i4.Future<bool> isApodSaved(String? apodDate) => (super.noSuchMethod(
        Invocation.method(
          #isApodSaved,
          [apodDate],
        ),
        returnValue: _i4.Future<bool>.value(false),
        returnValueForMissingStub: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<List<_i5.ApodModel>> fetchAllSavedApods() => (super.noSuchMethod(
        Invocation.method(
          #fetchAllSavedApods,
          [],
        ),
        returnValue: _i4.Future<List<_i5.ApodModel>>.value(<_i5.ApodModel>[]),
        returnValueForMissingStub:
            _i4.Future<List<_i5.ApodModel>>.value(<_i5.ApodModel>[]),
      ) as _i4.Future<List<_i5.ApodModel>>);
}
