// Mocks generated by Mockito 5.4.4 from annotations
// in flutter_clean_architecture/test/domain/usecases/bookmarks/is_apod_saved_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:flutter_clean_architecture/core/failure.dart' as _i5;
import 'package:flutter_clean_architecture/core/success.dart' as _i6;
import 'package:flutter_clean_architecture/domain/entities/apod_entity.dart'
    as _i7;
import 'package:flutter_clean_architecture/domain/repositories/bookmarks/bookmarks_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [BookmarksApodRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockBookmarksApodRepository extends _i1.Mock
    implements _i3.BookmarksApodRepository {
  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.ApodSave>> saveApod(
          _i7.ApodEntity? apod) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveApod,
          [apod],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i6.ApodSave>>.value(
            _FakeEither_0<_i5.Failure, _i6.ApodSave>(
          this,
          Invocation.method(
            #saveApod,
            [apod],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.Failure, _i6.ApodSave>>.value(
                _FakeEither_0<_i5.Failure, _i6.ApodSave>(
          this,
          Invocation.method(
            #saveApod,
            [apod],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.ApodSave>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.ApodRemove>> removeSavedApod(
          String? apodDate) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeSavedApod,
          [apodDate],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i6.ApodRemove>>.value(
            _FakeEither_0<_i5.Failure, _i6.ApodRemove>(
          this,
          Invocation.method(
            #removeSavedApod,
            [apodDate],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.Failure, _i6.ApodRemove>>.value(
                _FakeEither_0<_i5.Failure, _i6.ApodRemove>(
          this,
          Invocation.method(
            #removeSavedApod,
            [apodDate],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.ApodRemove>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, bool>> isApodSaved(String? apodDate) =>
      (super.noSuchMethod(
        Invocation.method(
          #isApodSaved,
          [apodDate],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, bool>>.value(
            _FakeEither_0<_i5.Failure, bool>(
          this,
          Invocation.method(
            #isApodSaved,
            [apodDate],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.Failure, bool>>.value(
                _FakeEither_0<_i5.Failure, bool>(
          this,
          Invocation.method(
            #isApodSaved,
            [apodDate],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, bool>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i7.ApodEntity>>>
      fetchAllSavedApods() => (super.noSuchMethod(
            Invocation.method(
              #fetchAllSavedApods,
              [],
            ),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, List<_i7.ApodEntity>>>.value(
                    _FakeEither_0<_i5.Failure, List<_i7.ApodEntity>>(
              this,
              Invocation.method(
                #fetchAllSavedApods,
                [],
              ),
            )),
            returnValueForMissingStub:
                _i4.Future<_i2.Either<_i5.Failure, List<_i7.ApodEntity>>>.value(
                    _FakeEither_0<_i5.Failure, List<_i7.ApodEntity>>(
              this,
              Invocation.method(
                #fetchAllSavedApods,
                [],
              ),
            )),
          ) as _i4.Future<_i2.Either<_i5.Failure, List<_i7.ApodEntity>>>);
}
